---
- name: Update repositories cache on Ubuntu
  apt:
    update_cache: true
  become: true

- name: Install required packages
  package:
    name: '{{ item }}'
    state: present
  become: true
  with_items: '{{ packages }}'

- name: Remove temporary working directory
  file:
    path: "{{ rclone_setup_tmp_dir }}"
    state: absent
  tags:
    - molecule-idempotence-notest

- name: Create temporary working directory
  file:
    path: "{{ rclone_setup_tmp_dir }}"
    state: directory
    mode: '0775'

- name: Do beta install
  include_tasks: beta.yml
  when: rclone_release == 'beta'

- name: Do stable install
  include_tasks: stable.yml
  when: rclone_release == 'stable'

- name: Get list of files extracted from the rclone archive
  find:
    path: "{{ rclone_setup_tmp_dir }}"
    depth: 2
    file_type: directory
  register: rclone_archive

- name: Copy rclone binary
  copy:
    src: "{{ rclone_setup_tmp_dir }}/rclone-v{{ rclone_version }}-linux-{{ rclone_arch }}/rclone"
    dest: "/usr/local/bin/rclone"
    mode: '0755'
    owner: root
    group: root
    remote_src: true
  become: true

- name: Make dir for local manpages
  file:
    path: '{{ man_pages.path }}'
    state: directory
    mode: '0775'
    owner: '{{ man_pages.owner }}'
    group: '{{ man_pages.group }}'
  become: true
  when: install_manpages

- name: Copy rclone manpage
  copy:
    src: "{{ rclone_setup_tmp_dir }}/rclone-v{{ rclone_version }}-linux-{{ rclone_arch }}/rclone.1"
    dest: "{{ man_pages.path }}/rclone.1"
    mode: '0644'
    owner: root
    group: root
    remote_src: true
  become: true
  when: install_manpages

- name: Update mandb
  command: mandb
  become: true
  changed_when: false
  when: install_manpages
